In [30]:
import os 
import sys 
import ipynbname
import fnmatch
from pathlib import Path

import logging
from dotenv import load_dotenv
load_dotenv()

python_dir=os.getenv('python_dir')

if python_dir not in sys.path: 
    print(f"adding {python_dir} to sys path")
    sys.path.append(python_dir)

from common_utils import setup_logger
log_dir=os.getenv('log_dir')
log_file=os.path.join(log_dir, f"{ipynbname.name()}.log")
setup_logger('INFO',log_file)

logging.info(f"start  {ipynbname.name()}")

In [31]:
from pathlib import Path 
tmp_dir=os.getenv('tmp_dir')
workspace_dir=os.path.join(tmp_dir, "aimpro",f"{os.getpid()}")
Path(workspace_dir).mkdir(parents=True,exist_ok=True)
workspace_dir
#workspace_dir="/Users/feng/workspace/runtime/tmp/aimpro/29403"

'/tmp/aimpro/1613'

In [32]:
video_file_ext="MP4"
extract_fps=3
extract_img_fmt="jpg"
detection_chunk_size=60
pip=True

In [ ]:
# import pyperclip
# import os 
# raw_video_dir  = os.getenv('raw_video_dir')
# left_video_dir=os.path.join(raw_video_dir, 'left')
# right_video_dir=os.path.join(raw_video_dir, 'right')

# def file_sort_key(f):
#     name=os.path.basename(f)
#     name=name.split('.')[0].split('_')[-1]
#     return int(name)

# def gen_concat_cmd(video_dir, concat_file_name): 
#     files=fnmatch.filter(os.listdir(video_dir), f"*.{video_file_ext}")
#     files=[os.path.join(video_dir, f) for f in files ]
#     files=sorted(files, key=file_sort_key)
#     list_file_name=os.path.join(workspace_dir, f"{concat_file_name}.list.txt")
#     with open(list_file_name, 'w') as h : 
#         for f in files:
#             h.write(f"file '{f}' \n")
#     txt=  f"ffmpeg -f concat -safe 0 -i {list_file_name} -c copy {os.path.join(workspace_dir, concat_file_name)}"
#     pyperclip.copy(txt)
#     return txt

In [28]:
# cmd=gen_concat_cmd(left_video_dir, 'left_all_in_one.MP4')
# !{cmd}

In [29]:
# cmd =gen_concat_cmd(right_video_dir, 'right_all_in_one.MP4')
# !{cmd}

In [34]:
left_videos=fnmatch.filter(os.listdir(left_video_dir), f"*.MOV")
right_videos=fnmatch.filter(os.listdir(right_video_dir), f"*.{video_file_ext}")
left_videos=sorted(left_videos, key=file_sort_key)
right_videos=sorted(right_videos, key=file_sort_key)

left_videos , right_videos

(['IMG_4844.MOV', 'IMG_4845.MOV', 'IMG_4846.MOV'],
 ['20260619205546_000024.MP4',
  '20260619210856_000025.MP4',
  '20260619212244_000026.MP4'])

In [35]:

# left_video_file=os.path.join(raw_video_dir, 'left','20260516181012_000004.MP4')
# right_video_file=os.path.join(raw_video_dir, 'right','r_20260516181403_000006.MP4')
# left_video_file=os.path.join(workspace_dir, 'left_all_in_one.MP4')
# right_video_file=os.path.join(workspace_dir, 'right_all_in_one.MP4')
quater=1
left_video_file=os.path.join(left_video_dir, left_videos[quater-1])
right_video_file=os.path.join(right_video_dir, right_videos[quater-1])
# left_video_file=os.path.join(workspace_dir, "left_all_in_one.MP4")
# right_video_file=os.path.join(workspace_dir, "right_all_in_one.MP4")
left_video_file, right_video_file

('/mnt/c/data/temp/aimpro_raw_video/left/IMG_4844.MOV',
 '/mnt/c/data/temp/aimpro_raw_video/right/20260619205546_000024.MP4')

In [36]:
from video.synchronizer import * 
raw_offset, meaning = find_offset_seconds(workspace_dir,left_video_file, right_video_file)
offset=round(raw_offset)
raw_offset, offset, meaning

(-1.998125, -2, 'video B started 1.998125 earlier than video A.')

In [37]:
from video.ffmpeg_wrapper import * 
left_video_duration= get_video_duration(left_video_file)
right_video_duration= get_video_duration(right_video_file)
left_video_duration,right_video_duration

(709.176667, 709.933333)

In [38]:
left_frames_dir=os.path.join(workspace_dir, 'left')
Path(left_frames_dir).mkdir(parents=True, exist_ok=True)

right_frames_dir=os.path.join(workspace_dir, 'right')
Path(right_frames_dir).mkdir(parents=True, exist_ok=True)

In [39]:
def get_start_end_time(offset, left_duration, right_duration): 
    if offset <0: 
        # right start early
        right_start=-1*offset
        new_right_duration =  right_duration+offset 
        min_duration =min(left_duration, new_right_duration)
        return 0, min_duration, right_start, right_start+min_duration

    elif offset>0: 
        left_start=offset 
        new_left_duration = left_duration-offset
        min_duration=min(new_left_duration, right_duration)
        return left_start, left_start+ min_duration, 0, min_duration
ts= get_start_end_time(offset, left_video_duration, right_video_duration)
ts =[format_seconds_to_hhmmss(t) for t in ts]
left_start, left_end, right_start, right_end= ts[0],ts[1],ts[2],ts[3]
left_start, left_end, right_start, right_end

('00:00:00', '00:11:47.933', '00:00:02', '00:11:49.933')

In [40]:
file_name_pattern=f"%d.{extract_img_fmt}"
output = os.path.join(left_frames_dir, file_name_pattern)
cmd=f"ffmpeg -ss {left_start} -to {left_end} -i {left_video_file} -vf scale=1280:720,fps={extract_fps} {output}"
out =!{cmd}
print(out[:20])

['ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers', '  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)', '  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared', '  libavutil      56. 70.100 / 56. 70.100', '  libavcodec     58.134.100 / 58.134.100', '  libavformat    58. 76.100 / 58. 76.100', '  libavdevice    58. 13.100 / 58. 13.100', '  libavfilter     7.110.100 /  7.110.100', '  libswscale      5.  9.100 /  5.  9.100', '  libswresample   3.  9.100 /  3.  9.100', '  libpostproc    55.  9.100 / 55.  9.100', "Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/mnt/c/data/temp/aimpro_raw_video/left/IMG_4844.MOV':", '  Metadata:', '    major_brand     : qt  ', '    minor_version   : 0', '    compatible_brands: qt  ', '    creation_time   : 2026-06-19T10:54:18.000000Z', '    com.apple.quicktime.location.accuracy.horizontal: 10.392625', '    com.apple.quicktime.full-frame-rate-playback-intent: 0', '    com.apple.quicktime.location.ISO6709: -37.7734+145.1927+087.223/']

In [41]:
output = os.path.join(right_frames_dir, file_name_pattern)
cmd=f"ffmpeg -ss {right_start} -to {right_end} -i {right_video_file} -vf scale=1280:720,fps={extract_fps} {output}"
out =!{cmd}
print(out[:1])

['ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers']

In [42]:
def rename_img_file_to_seconds_index(fd):
    files = fnmatch.filter(os.listdir(fd), f"*.{extract_img_fmt}")
    for f in files: 
        parts=f.split(".")
        file_index, ext=int(parts[0])-1, parts[1]
        second, index_in_second=divmod(file_index,extract_fps)
        new_file_name=f"{second}-{index_in_second}.{ext}"
        shutil.move(os.path.join(fd,f), os.path.join(fd,new_file_name))
rename_img_file_to_seconds_index(left_frames_dir)
rename_img_file_to_seconds_index(right_frames_dir)

In [43]:
from ml.detectors import * 
import pandas  as pd 

detection_chunk_size=240

def detect_basketball_and_players(video_frame_dir): 
    files=fnmatch.filter(os.listdir(video_frame_dir), f"*.{extract_img_fmt}")
    df=pd.DataFrame(data=files, columns=["file_name"])
    df['chunk']=range(df.shape[0])
    df['chunk']=df.chunk//detection_chunk_size
    def detect_chunk(gdf):
        logging.info(f"object detection chuck : {gdf.name}")
        files=[os.path.join(video_frame_dir,f) for f in gdf.file_name] 
        results=detect_objects_on_multiple_images(files)
        trios=[analyze_result(r) for r in results]
        num_of_basketballs, num_of_players , num_of_possessions, total_object_area= zip (*trios)
        gdf['has_baseketball']=num_of_basketballs
        gdf['has_baseketball']=gdf.has_baseketball>0
        gdf['has_possession']=num_of_possessions
        gdf['has_possession']=gdf.has_possession>0
        gdf['total_num_of_players']=num_of_players
        gdf['total_object_area']=total_object_area
        
        return gdf 
    ret= df.groupby('chunk').apply(detect_chunk)
    ret.sort_values(by="file_name", inplace=True)
    ret.to_csv(os.path.join(video_frame_dir, "frame_information.csv"), index=False)
    # return pd.concat(dfs)
    return ret
detect_basketball_and_players(left_frames_dir).shape , detect_basketball_and_players(right_frames_dir).shape

((2124, 5), (2124, 5))

In [51]:
def agg_frame_information_df(df):
    def extract_second_and_index(fn):
        parts = fn.split(".")[0].split("-") 
        return parts[0], parts[1]
    pairs=df.file_name.apply(extract_second_and_index)
    df['second'], df["index_within_second"]=zip (*pairs)
    df['second'], df["index_within_second"]=df.second.astype(int), df.index_within_second.astype(int)
    adf=df.groupby('second').agg(
        {
            "has_baseketball":'any',
            "total_num_of_players":'sum' ,
            "has_possession":'any', 
            "total_object_area":'sum'   
        } 
    ).reset_index()
    adf.sort_values(by='second', inplace=True)
    return adf 

left_frames_df=pd.read_csv(os.path.join(left_frames_dir, "frame_information.csv"), index_col=None)
left_frames_df=agg_frame_information_df(left_frames_df)

right_frames_df=pd.read_csv(os.path.join(right_frames_dir, "frame_information.csv"), index_col=None)
right_frames_df=agg_frame_information_df(right_frames_df)

left_frames_df.shape, right_frames_df.shape

((708, 5), (708, 5))

In [45]:
left_frames_df.head(2)

,second,has_baseketball,total_num_of_players,has_possession,total_object_area
0,0,False,0,False,0.000000
1,1,True,4,False,33395.107422

In [ ]:
mdf=left_frames_df.merge(right_frames_df, how='inner', on='second', suffixes=("_l","_r"))
mdf.head(2)

,second,has_baseketball_l,total_num_of_players_l,has_possession_l,total_object_area_l,has_baseketball_r,total_num_of_players_r,has_possession_r,total_object_area_r
0,0,False,0,False,0.000000,False,8,False,53716.728516
1,1,True,4,False,33395.107422,False,6,False,28876.483398

In [ ]:
def smooth_left_right(ac): 
    s=ac.copy()
    prev,nxt=s.shift(1),s.shift(-1)
    mask=(s!=prev) & (s!=nxt) & (prev==nxt)
    ret=s.copy()
    ret[mask]=prev[mask]

    #force setting the first to the same as second; 
    #the last to the same as the second last;
    if ret.size>2:
        ret.iloc[0]=ret.iloc[1]
        ret.iloc[-1]=ret.iloc[-2]

    return ret 

def decide_active_camera(r):
    # is_timeout_or_break=r['total_num_of_players_l']<=2 and r['total_num_of_players_r']<=2
    # if is_timeout_or_break: 
    #      return "skip"
    
    ball_on_left= r["has_possession_l"] or r["has_baseketball_l"]
    ball_on_right= r["has_possession_r"] or r["has_baseketball_r"]

    only_on_left=ball_on_left and not ball_on_right
    only_on_right=ball_on_right and not ball_on_left

    if only_on_left:
         return 'left'
    elif only_on_right: 
        return 'right'
    else: 
        if r['total_num_of_players_l']>r['total_num_of_players_r']:
                return 'left'
        elif r['total_num_of_players_l']<r['total_num_of_players_r']:
                return 'right'
        else:
            if r['total_object_area_l']>r['total_object_area_r']:
                    return 'left'
            elif r['total_object_area_l']<r['total_object_area_r']:
                    return 'right'
    return None

mdf.sort_values(by='second', ascending=True, inplace=True)

mdf['active_camera']=mdf.apply(decide_active_camera, axis=1)
mdf.ffill(inplace=True)

#double smooth 
mdf['active_camera']=smooth_left_right(mdf.active_camera)
mdf['active_camera']=smooth_left_right(mdf.active_camera)
mdf['active_camera']=smooth_left_right(mdf.active_camera)
mdf.to_csv(os.path.join(workspace_dir,'active_camera.csv'), index=False)
mdf.head(2)

,second,has_baseketball_l,total_num_of_players_l,has_possession_l,total_object_area_l,has_baseketball_r,total_num_of_players_r,has_possession_r,total_object_area_r,active_camera
0,0,False,0,False,0.000000,False,8,False,53716.728516,left
1,1,True,4,False,33395.107422,False,6,False,28876.483398,left

In [48]:
mdf=pd.read_csv(os.path.join(workspace_dir,'active_camera.csv'), index_col=None)

def gen_hhmmss(side, offset, second): 
    #if offset <0 , then right start early; otherwise left start early. 
    if offset<0: 
        if side =='right': 
            second =float(second) +offset*(-1)
    else: 
        if side=='left': 
            second =float(second) +offset
    return format_seconds_to_hhmmss(second) 

def gen_ffmpeg_extract_commands(mdf):
    def gen_cmd(start_r,last_r): 
        if start_r.active_camera=='left':
            start_hhmmss=gen_hhmmss("left", offset, start_r.second)
            to_hhmmss=gen_hhmmss("left", offset, last_r.second)
            video_file_name=left_video_file
        else:
            start_hhmmss=gen_hhmmss("right", offset, start_r.second)
            to_hhmmss=gen_hhmmss("right", offset, last_r.second)
            video_file_name=right_video_file
        cmd1 = f"ffmpeg -ss {start_hhmmss} -to {to_hhmmss} -i {video_file_name}  -c copy part_to_be_replaced"
        return cmd1
    
    start_r, last_r=None, None  
    cmds=[]
    for r in mdf.itertuples():
        if start_r is None: 
            start_r, last_r=r, r 
            continue
        else: 
            if r.active_camera!=last_r.active_camera: 
                #need swtich. 
                cmds.append(gen_cmd(start_r, last_r))
                start_r, last_r=r, r 
            else:
                last_r=r 

    if start_r and last_r: 
        cmds.append(gen_cmd(start_r,last_r))       
    return cmds 

def gen_ffmpeg_extract_commands_with_pip(mdf):
    def gen_cmd(start_r,last_r): 
        
        if start_r.active_camera=='left':
            start_hhmmss=gen_hhmmss("left", offset, start_r.second)
            to_hhmmss=gen_hhmmss("left", offset, last_r.second)
            video_file_name=left_video_file

            pip_start_hhmmss=gen_hhmmss("right", offset, start_r.second)
            pip_to_hhmmss=gen_hhmmss("right", offset, last_r.second)
            pip_video_file_name=right_video_file
        else:
            start_hhmmss=gen_hhmmss("right", offset, start_r.second)
            to_hhmmss=gen_hhmmss("right", offset, last_r.second)
            video_file_name=right_video_file
            
            pip_start_hhmmss=gen_hhmmss("left", offset, start_r.second)
            pip_to_hhmmss=gen_hhmmss("left", offset, last_r.second)
            pip_video_file_name=left_video_file
            
        cmd1 = f"ffmpeg -ss {start_hhmmss} -to {to_hhmmss} -i {video_file_name}  -c copy part_to_be_replaced"
        cmd2 = f"ffmpeg -ss {pip_start_hhmmss} -to {pip_to_hhmmss} -i {pip_video_file_name}  -c copy {start_r.active_camera}-part_to_be_replaced" 
        return (cmd1,cmd2)
    
    start_r, last_r=None, None  
    cmds=[]
    for r in mdf.itertuples():
        if start_r is None: 
            start_r, last_r=r, r 
            continue
        else: 
            if r.active_camera!=last_r.active_camera: 
                #need swtich. 
                cmds.append(gen_cmd(start_r, last_r))
                start_r, last_r=r, r 
            else:
                last_r=r 

    if start_r and last_r: 
        cmds.append(gen_cmd(start_r,last_r))       
    return cmds 

if pip: 
    extract_cmds = gen_ffmpeg_extract_commands_with_pip(mdf)
    c, c_pip =extract_cmds[0]
    print(c)
    print(c_pip)
else: 
    extract_cmds = gen_ffmpeg_extract_commands(mdf)
    print(extract_cmds[0])

ffmpeg -ss 00:00:00 -to 00:00:04 -i /mnt/c/data/temp/aimpro_raw_video/left/IMG_4844.MOV  -c copy part_to_be_replaced
ffmpeg -ss 00:00:02 -to 00:00:06 -i /mnt/c/data/temp/aimpro_raw_video/right/20260619205546_000024.MP4  -c copy left-part_to_be_replaced

In [49]:
import pyperclip
from itertools import chain
def post_process_extract_cmds(extract_cmds): 
    def rpl(index, cmd): 
        part=os.path.join(workspace_dir, f"part-{index}.MP4")
        return cmd.replace('part_to_be_replaced', part)
    extract_cmds= [rpl(i,c) for i, c in enumerate(extract_cmds) ]
    text="\n".join(extract_cmds)
    with open(os.path.join(workspace_dir,'extract_part.sh'), 'w') as h: 
        h.write(text)
    
    return extract_cmds

def post_process_extract_cmds_pip(extract_cmds): 
    def rpl(index, cmd_pair): 
        c,c_pip=cmd_pair
        part=os.path.join(workspace_dir, f"part-{index}.MP4")
        c = c.replace('part_to_be_replaced', part)

        #for pip a bit tricky. 
        active_camera_and_place_holder=c_pip.split(" ")[-1]
        active_camera=active_camera_and_place_holder.split("-")[0]
        part=os.path.join(workspace_dir, f"pip-{active_camera}-part-{index}.MP4")
        c_pip = c_pip.replace(active_camera_and_place_holder, part)
        return c, c_pip
    extract_cmds= [rpl(i,c) for i, c in enumerate(extract_cmds) ]
    extract_cmds = list(chain.from_iterable(extract_cmds))
    print(len(extract_cmds))
    text="\n".join(extract_cmds)
    with open(os.path.join(workspace_dir,'extract_part.sh'), 'w') as h: 
        h.write(text)
    
    return extract_cmds

if pip:
    process_extract_cmds = post_process_extract_cmds_pip(extract_cmds)
else: 
    process_extract_cmds=post_process_extract_cmds(extract_cmds)

! bash {workspace_dir}/extract_part.sh

146
ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/mnt/c/data/temp/aimpro_raw_video/left/IMG_4844.MOV':
  Metadata:
    major_brand     : qt
    minor_version   : 0
    compatible_brands: qt
    creation_time   : 2026-06-19T10:54:18.000000Z
    com.apple.quicktime.location.accuracy.horizontal: 10.392625
    com.apple.quicktime.full-frame-rate-playback-intent: 0
    com.apple.quicktime.location.ISO6709: -37.7734+145.1927+087.223/
    com.apple.quicktime.make: Apple
    com.apple.quicktime.model: iPhone 12
    com.apple.quicktime.software: 26.5
    com.apple.quicktime.creationdate: 2026-06-19T20:54:18+1000
  Duration: 00:11:49.18, start: 0.000000, bitrate: 15033 kb/s
  Stream #0:0(und): Video: hevc (Main) (hvc1 / 0x31637668), yuv420p(tv, bt709), 1920x1080, 14713 kb/s, 59.95 fps, 59.94 tbr, 600 tbn, 600 tbc (default)
    Metadata:
      creation_time   : 2026-06-19T10:54:18.000000Z
      handler_name    : Core Media Video
      vendor_id       : [0][0][0][0]
      encoder         : HEVC
  Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 205 kb/s (default)
    Metadata:
      creation_time   : 2026-06-19T10:54:18.000000Z
      handler_name    : Core Media Audio
      vendor_id       : [0][0][0][0]
  Stream #0:2(und): Data: none (mebx / 0x7862656D) (default)
    Metadata:
      creation_time   : 2026-06-19T10:54:18.000000Z
      handler_name    : Core Media Metadata
  Stream #0:3(und): Data: none (mebx / 0x7862656D), 2 kb/s (default)
    Metadata:
      creation_time   : 2026-06-19T10:54:18.000000Z
      handler_name    : Core Media Metadata
  Stream #0:4(und): Data: none (mebx / 0x7862656D), 88 kb/s (default)
    Metadata:
      creation_time   : 2026-06-19T10:54:18.000000Z
      handler_name    : Core Media Metadata
  Stream #0:5(und): Data: none (mebx / 0x7862656D) (default)
    Metadata:
      creation_time   : 2026-06-19T10:54:18.000000Z
      handler_name    : Core Media Metadata
Output #0, mp4, to '/tmp/aimpro/1613/part-0.MP4':
  Metadata:
    major_brand     : qt
    minor_version   : 0
    compatible_brands: qt
    com.apple.quicktime.creationdate: 2026-06-19T20:54:18+1000
    com.apple.quicktime.location.accuracy.horizontal: 10.392625
    com.apple.quicktime.full-frame-rate-playback-intent: 0
    com.apple.quicktime.location.ISO6709: -37.7734+145.1927+087.223/
    com.apple.quicktime.make: Apple
    com.apple.quicktime.model: iPhone 12
    com.apple.quicktime.software: 26.5
    encoder         : Lavf58.76.100
  Stream #0:0(und): Video: hevc (Main) (hvc1 / 0x31637668), yuv420p(tv, bt709), 1920x1080, q=2-31, 14713 kb/s, 59.95 fps, 59.94 tbr, 19200 tbn, 600 tbc (default)
    Metadata:
      creation_time   : 2026-06-19T10:54:18.000000Z
      handler_name    : Core Media Video
      vendor_id       : [0][0][0][0]
      encoder         : HEVC
  Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 205 kb/s (default)
    Metadata:
      creation_time   : 2026-06-19T10:54:18.000000Z
      handler_name    : Core Media Audio
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=  242 fps=0.0 q=-1.0 Lsize=    7630kB time=00:00:03.98 bitrate=15672.4kbits/s speed=34.9x
video:7521kB audio:101kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.105542%
ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/mnt/c/data/temp/aimpro_raw_video/right/20260619205546_000024.MP4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isomavc1mp42
    creation_time   : 2026-06-19T13:07:36.000000Z
  Duration: 00:11:49.93, start: 0.000000, bitrate: 10975 kb/s
  Stream #0:0(eng): Video: hevc (Main) (hvc1 / 0x31637668), yuvj420p(pc, bt709), 1920x1080, 10813 kb/s, 60 fps, 60 tbr, 92400 tbn, 60 tbc (default)
    Metadata:
      creation_time   : 2026-06-19T13:07:36.000000Z
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 32000 Hz, mono, fltp, 62 kb/s (default)
    Metadata:
      creation_time   : 2026-06-19T13:07:36.000000Z
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
Output #0, mp4, to '/tmp/aimpro/1613/pip-left-part-0.MP4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isomavc1mp42
    encoder         : Lavf58.76.100
  Stream #0:0(eng): Video: hevc (Main) (hvc1 / 0x31637668), yuvj420p(pc, bt709), 1920x1080, q=2-31, 10813 kb/s, 60 fps, 60 tbr, 92400 tbn, 92400 tbc (default)
    Metadata:
      creation_time   : 2026-06-19T13:07:36.000000Z
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 32000 Hz, mono, fltp, 62 kb/s (default)
    Metadata:
      creation_time   : 2026-06-19T13:07:36.000000Z
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=  240 fps=0.0 q=-1.0 Lsize=    5313kB time=00:00:03.98 bitrate=10924.2kbits/s speed=44.3x
video:5278kB audio:31kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.077225%
ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/mnt/c/data/temp/aimpro_raw_video/right/20260619205546_000024.MP4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isomavc1mp42
    creation_time   : 2026-06-19T13:07:36.000000Z
  Duration: 00:11:49.93, start: 0.000000, bitrate: 10975 kb/s
  Stream #0:0(eng): Video: hevc (Main) (hvc1 / 0x31637668), yuvj420p(pc, bt709), 1920x1080, 10813 kb/s, 60 fps, 60 tbr, 92400 tbn, 60 tbc (default)
    Metadata:
      creation_time   : 2026-06-19T13:07:36.000000Z
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 32000 Hz, mono, fltp, 62 kb/s (default)
    Metadata:
      creation_time   : 2026-06-19T13:07:36.000000Z
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
Output #0, mp4, to '/tmp/aimpro/1613/part-1.MP4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isomavc1mp42
    encoder         : Lavf58.76.100
  Stream #0:0(eng): Video: hevc (Main) (hvc1 / 0x31637668), yuvj420p(pc, bt709), 1920x1080, q=2-31, 10813 kb/s, 60 fps, 60 tbr, 92400 tbn, 92400 tbc (default)
    Metadata:
      creation_time   : 2026-06-19T13:07:36.000000Z
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 32000 Hz, mono, fltp, 62 kb/s (default)
    Metadata:
      creation_time   : 2026-06-19T13:07:36.000000Z
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame= 1020 fps=0.0 q=-1.0 Lsize=   22584kB time=00:00:16.98 bitrate=10893.5kbits/s speed=53.2x
video:22441kB audio:130kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.056462%
ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/mnt/c/data/temp/aimpro_raw_video/left/IMG_4844.MOV':
  Metadata:
    major_brand     : qt
    minor_version   : 0
    compatible_brands: qt
    creation_time   : 2026-06-19T10:54:18.000000Z
    com.apple.quicktime.location.accuracy.horizontal: 10.392625
    com.apple.quicktime.full-frame-rate-playback-intent: 0
    com.apple.quicktime.location.ISO6709: -37.7734+145.1927+087.223/
    com.apple.quicktime.make: Apple
    com.apple.quicktime.model: iPhone 12
    com.apple.quicktime.software: 26.5
    com.apple.quicktime.creationdate: 2026-06-19T20:54:18+1000
  Duration: 00:11:49.18, start: 0.000000, bitrate: 15033 kb/s
  Stream #0:0(und): Video: hevc (Main) (hvc1 / 0x31637668), yuv420p(tv, bt709), 1920x1080, 14713 kb/s, 59.95 fps, 59.94 tbr, 600 tbn, 600 tbc (default)
    Metadata:
      creation_time   : 2026-06-19T10:54:18.000000Z
      handler_name    : Core Media Video
      vendor_id       : [0][0][0][0]
      encoder         : HEVC
  Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 205 kb/s (default)
    Metadata:
      creation_time   : 2026-06-19T10:54:18.000000Z
      handler_name    : Core Media Audio
      vendor_id       : [0][0][0][0]
  Stream #0:2(und): Data: none (mebx / 0x7862656D) (default)
    Metadata:
      creation_time   : 2026-06-19T10:54:18.000000Z
      handler_name    : Core Media Metadata
  Stream #0:3(und): Data: none (mebx / 0x7862656D), 2 kb/s (default)
    Metadata:
      creation_time   : 2026-06-19T10:54:18.000000Z
      handler_name    : Core Media Metadata
  Stream #0:4(und): Data: none (mebx / 0x7862656D), 88 kb/s (default)
    Metadata:
      creation_time   : 2026-06-19T10:54:18.000000Z
      handler_name    : Core Media Metadata
  Stream #0:5(und): Data: none (mebx / 0x7862656D) (default)
    Metadata:
      creation_time   : 2026-06-19T10:54:18.000000Z
      handler_name    : Core Media Metadata
Output #0, mp4, to '/tmp/aimpro/1613/pip-right-part-1.MP4':
  Metadata:
    major_brand     : qt
    minor_version   : 0
    compatible_brands: qt
    com.apple.quicktime.creationdate: 2026-06-19T20:54:18+1000
    com.apple.quicktime.location.accuracy.horizontal: 10.392625
    com.apple.quicktime.full-frame-rate-playback-intent: 0
    com.apple.quicktime.location.ISO6709: -37.7734+145.1927+087.223/
    com.apple.quicktime.make: Apple
    com.apple.quicktime.model: iPhone 12
    com.apple.quicktime.software: 26.5
    encoder         : Lavf58.76.100
  Stream #0:0(und): Video: hevc (Main) (hvc1 / 0x31637668), yuv420p(tv, bt709), 1920x1080, q=2-31, 14713 kb/s, 59.95 fps, 59.94 tbr, 19200 tbn, 600 tbc (default)
    Metadata:
      creation_time   : 2026-06-19T10:54:18.000000Z
      handler_name    : Core Media Video
      vendor_id       : [0][0][0][0]
      encoder         : HEVC
  Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 205 kb/s (default)
    Metadata:
      creation_time   : 2026-06-19T10:54:18.000000Z
      handler_name    : Core Media Audio
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame= 1044 fps=0.0 q=-1.0 Lsize=   30601kB time=00:00:16.99 bitrate=14752.1kbits/s speed=45.1x
video:30135kB audio:436kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.097654%
ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/mnt/c/data/temp/aimpro_raw_video/left/IMG_4844.MOV':
  Metadata:
    major_brand     : qt
    minor_version   : 0
    compatible_brands: qt
    creation_time   : 2026-06-19T10:54:18.000000Z
    com.apple.quicktime.location.accuracy.horizontal: 10.392625
    com.apple.quicktime.full-frame-rate-playback-intent: 0
    com.apple.quicktime.location.ISO6709: -37.7734+145.1927+087.223/
    com.apple.quicktime.make: Apple
    com.apple.quicktime.model: iPhone 12
    com.apple.quicktime.software: 26.5
    com.apple.quicktime.creationdate: 2026-06-19T20:54:18+1000
  Duration: 00:11:49.18, start: 0.000000, bitrate: 15033 kb/s
  Stream #0:0(und): Video: hevc (Main) (hvc1 / 0x31637668), yuv420p(tv, bt709), 1920x1080, 14713 kb/s, 59.95 fps, 59.94 tbr, 600 tbn, 600 tbc (default)
    Metadata:
      creation_time   : 2026-06-19T10:54:18.000000Z
      handler_name    : Core Media Video
      vendor_id       : [0][0][0][0]

In [ ]:
def part_sort_key(fn):
    return int(fn.split(".")[0].split("-")[-1])

def produce_pip(part, pip_part): 
    #get active camera first. 
    # pip-right-part-8.MP4
    active_camera=pip_part.split("-")[1]
    output_part = f"with_pip_{part}"
    
    # Top-Left Corneroverlay=10:10
    # Top-Right Corneroverlay=W-w-10:10
    # Bottom-Left Corneroverlay=10:H-h-10
    # Bottom-Right Corneroverlay=W-w-10:H-h-10
    
    #place the overlay on the top left, if active camera is right. 
    #position_directive="overlay=20:20"
    position_directive="overlay=W-w-10:H-h-10"
    # if active_camera=='left': 
    #     #then place the pip at the right top corner. 
    #     position_directive="overlay=W-w-20:20"

    part =os.path.join(workspace_dir, part)
    pip_part=os.path.join(workspace_dir, pip_part)
    output_file=os.path.join(workspace_dir,output_part)

    #get the active camera first.                            "[1:v]scale=iw/4:-1, pad=iw+20:ih+20:10:10:color=white[pip];[0:v][pip]overlay=20:20:ts_sync_mode=vfr" 
    #return  f'ffmpeg -i {part} -i {pip_part} -filter_complex "[1:v]scale=iw/4:-1[pip];[0:v][pip]{position_directive}:shortest=1" -c:a copy {output_file}'
    return  f'ffmpeg -i {part} -i {pip_part} -filter_complex "[1:v]scale=iw/4:-1,pad=iw+5:ih+5:2:2:color=greenyellow [pip];[0:v][pip]{position_directive}:shortest=1" -c:a copy {output_file}'
    

    

if pip: 
    parts=fnmatch.filter(os.listdir(workspace_dir),"part*.MP4")
    pipparts =fnmatch.filter(os.listdir(workspace_dir), "pip*part*.MP4")
    parts.sort(key=part_sort_key)
    pipparts.sort(key=part_sort_key)
    main_pip_pairs=list(zip(parts,pipparts))
    for (p, pip) in main_pip_pairs: 
        cmd= produce_pip(p, pip )
        !{cmd}

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/tmp/aimpro/1613/part-0.MP4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf58.76.100
  Duration: 00:00:04.09, start: 0.000000, bitrate: 15292 kb/s
  Stream #0:0(und): Video: hevc (Main) (hvc1 / 0x31637668), yuv420p(tv, bt709), 1920x1080, 15262 kb/s, 59.95 fps, 59.94 tbr, 19200 tbn, 19200 tbc (default)
    Metadata:
      handler_name    : Core Media Video
      vendor_id       : [0][0][0][0]
  Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 205 kb/s (default)
    Metadata:
      handler_name    : Core Media Audio
      vendor_id       : [0][0][0][0]
Input #1, mov,mp4,m4a,3gp,3g2,mj2, from '/tmp/aimpro/1613/pip-left-part-0.MP4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf58.76.100
  Duration: 00:00:04.02, start: 0.000000, bitrate: 10837 kb/s
  Stream #1:0(eng): Video: hevc (Main) (hvc1 / 0x31637668), yuvj420p(pc, bt709), 1920x1080, 10808 kb/s, 60 fps, 60 tbr, 92400 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #1:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 32000 Hz, mono, fltp, 62 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 (hevc) -> overlay:main
  Stream #1:0 (hevc) -> scale
  overlay -> Stream #0:0 (libx264)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[swscaler @ 0x56770b03e480] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x56770b03e480] Warning: data is not aligned! This can lead to a speed loss
[libx264 @ 0x56770b010440] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x56770b010440] profile High, level 4.2, 4:2:0, 8-bit
[libx264 @ 0x56770b010440] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=18 lookahead_threads=3 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/tmp/aimpro/1613/with_pip_part-0.MP4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1920x1080, q=2-31, 59.94 fps, 60k tbn (default)
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
  Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 205 kb/s (default)
    Metadata:
      handler_name    : Core Media Audio
      vendor_id       : [0][0][0][0]
frame=  239 fps= 48 q=-1.0 Lsize=    1790kB time=00:00:03.98 bitrate=3677.1kbits/s speed=0.798x
video:1682kB audio:101kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.428667%
[libx264 @ 0x56770b010440] frame I:1     Avg QP:25.56  size:104080
[libx264 @ 0x56770b010440] frame P:60    Avg QP:25.18  size: 18625
[libx264 @ 0x56770b010440] frame B:178   Avg QP:28.66  size:  2808
[libx264 @ 0x56770b010440] consecutive B-frames:  0.4%  0.8%  0.0% 98.7%
[libx264 @ 0x56770b010440] mb I  I16..4: 10.6% 70.3% 19.0%
[libx264 @ 0x56770b010440] mb P  I16..4:  0.5%  1.3%  0.2%  P16..4: 41.7%  6.6%  4.5%  0.0%  0.0%    skip:45.1%
[libx264 @ 0x56770b010440] mb B  I16..4:  0.0%  0.0%  0.0%  B16..8: 22.2%  0.7%  0.1%  direct: 0.2%  skip:76.8%  L0:30.8% L1:67.4% BI: 1.8%
[libx264 @ 0x56770b010440] 8x8 transform intra:66.3% inter:85.6%
[libx264 @ 0x56770b010440] coded y,uvDC,uvAC intra: 55.2% 59.3% 20.0% inter: 5.1% 9.0% 0.3%
[libx264 @ 0x56770b010440] i16 v,h,dc,p: 20% 27% 11% 42%
[libx264 @ 0x56770b010440] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 18% 27% 17%  3%  5%  4% 14%  4%  6%
[libx264 @ 0x56770b010440] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 27% 29% 11%  4%  5%  5% 11%  5%  5%
[libx264 @ 0x56770b010440] i8c dc,h,v,p: 50% 25% 21%  5%
[libx264 @ 0x56770b010440] Weighted P-Frames: Y:1.7% UV:0.0%
[libx264 @ 0x56770b010440] ref P L0: 62.9% 12.7% 18.2%  6.2%  0.1%
[libx264 @ 0x56770b010440] ref B L0: 91.4%  6.6%  2.0%
[libx264 @ 0x56770b010440] ref B L1: 95.2%  4.8%
[libx264 @ 0x56770b010440] kb/s:3453.71
ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/tmp/aimpro/1613/part-1.MP4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf58.76.100
  Duration: 00:00:17.00, start: 0.000000, bitrate: 10882 kb/s
  Stream #0:0(eng): Video: hevc (Main) (hvc1 / 0x31637668), yuvj420p(pc, bt709), 1920x1080, 10813 kb/s, 60 fps, 60 tbr, 92400 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 32000 Hz, mono, fltp, 62 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
Input #1, mov,mp4,m4a,3gp,3g2,mj2, from '/tmp/aimpro/1613/pip-right-part-1.MP4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf58.76.100
  Duration: 00:00:17.04, start: 0.000000, bitrate: 14714 kb/s
  Stream #1:0(und): Video: hevc (Main) (hvc1 / 0x31637668), yuv420p(tv, bt709), 1920x1080, 14490 kb/s, 59.94 fps, 60 tbr, 19200 tbn, 19200 tbc (default)
    Metadata:
      handler_name    : Core Media Video
      vendor_id       : [0][0][0][0]
  Stream #1:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 209 kb/s (default)
    Metadata:
      handler_name    : Core Media Audio
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 (hevc) -> overlay:main
  Stream #1:0 (hevc) -> scale
  overlay -> Stream #0:0 (libx264)
  Stream #1:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[swscaler @ 0x62dd8164d700] Warning: data is not aligned! This can lead to a speed loss
[libx264 @ 0x62dd7f67bdc0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x62dd7f67bdc0] profile High, level 4.2, 4:2:0, 8-bit
[libx264 @ 0x62dd7f67bdc0] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=18 lookahead_threads=3 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/tmp/aimpro/1613/with_pip_part-1.MP4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuvj420p(pc, bt709, progressive), 1920x1080, q=2-31, 60 fps, 15360 tbn (default)
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
  Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 209 kb/s (default)
    Metadata:
      handler_name    : Core Media Audio
      vendor_id       : [0][0][0][0]
frame= 1020 fps= 50 q=-1.0 Lsize=   12481kB time=00:00:16.99 bitrate=6016.9kbits/s speed=0.826x
video:12017kB audio:436kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.224880%
[libx264 @ 0x62dd7f67bdc0] frame I:5     Avg QP:22.26  size:253893
[libx264 @ 0x62dd7f67bdc0] frame P:267   Avg QP:24.96  size: 30093
[libx264 @ 0x62dd7f67bdc0] frame B:748   Avg QP:30.95  size:  4011
[libx264 @ 0x62dd7f67bdc0] consecutive B-frames:  0.8%  4.1%  0.6% 94.5%
[libx264 @ 0x62dd7f67bdc0] mb I  I16..4:  4.9% 59.6% 35.5%
[libx264 @ 0x62dd7f67bdc0] mb P  I16..4:  0.6%  2.1%  0.5%  P16..4: 34.6%  8.9%  5.7%  0.0%  0.0%    skip:47.6%
[libx264 @ 0x62dd7f67bdc0] mb B  I16..4:  0.0%  0.1%  0.0%  B16..8: 23.5%  1.5%  0.5%  direct: 0.4%  skip:74.0%  L0:52.5% L1:43.2% BI: 4.3%
[libx264 @ 0x62dd7f67bdc0] 8x8 transform intra:63.7% inter:76.3%
[libx264 @ 0x62dd7f67bdc0] coded y,uvDC,uvAC intra: 71.1% 84.2% 45.5% inter: 6.1% 7.9% 0.8%
[libx264 @ 0x62dd7f67bdc0] i16 v,h,dc,p: 22% 35%  7% 36%
[libx264 @ 0x62dd7f67bdc0] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 22% 26% 12%  5%  5%  6%  6%  7% 10%
[libx264 @ 0x62dd7f67bdc0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 25% 31%  9%  4%  5%  6%  8%  5%  8%
[libx264 @ 0x62dd7f67bdc0] i8c dc,h,v,p: 38% 27% 24% 11%
[libx264 @ 0x62dd7f67bdc0] Weighted P-Frames: Y:1.5% UV:0.0%
[libx264 @ 0x62dd7f67bdc0] ref P L0: 60.7% 18.0% 15.4%  5.8%  0.1%
[libx264 @ 0x62dd7f67bdc0] ref B L0: 92.7%  6.2%  1.1%
[libx264 @ 0x62dd7f67bdc0] ref B L1: 96.5%  3.5%
[libx264 @ 0x62dd7f67bdc0] kb/s:5790.51
ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/tmp/aimpro/1613/part-2.MP4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf58.76.100
  Duration: 00:00:07.04, start: 0.000000, bitrate: 16461 kb/s
  Stream #0:0(und): Video: hevc (Main) (hvc1 / 0x31637668), yuv420p(tv, bt709), 1920x1080, 16217 kb/s, 59.95 fps, 59.94 tbr, 19200 tbn, 19200 tbc (default)
    Metadata:
      handler_name    : Core Media Video
      vendor_id       : [0][0][0][0]
  Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 229 kb/s (default)
    Metadata:
      handler_name    : Core Media Audio
      vendor_id       : [0][0][0][0]
Input #1, mov,mp4,m4a,3gp,3g2,mj2, from '/tmp/aimpro/1613/pip-left-part-2.MP4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf58.76.100
  Duration: 00:00:07.00, start: 0.000000, bitrate: 10883 kb/s
  Stream #1:0(eng): Video: hevc (Main) (hvc1 / 0x31637668), yuvj420p(pc, bt709), 1920x1080, 10813 kb/s, 60 fps, 60 tbr, 92400 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #1:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 32000 Hz, mono, fltp, 62 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 (hevc) -> overlay:main
  Stream #1:0 (hevc) -> scale
  overlay -> Stream #0:0 (libx264)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[swscaler @ 0x563af0dcd600] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x563af0dcd600] Warning: data is not aligned! This can lead to a speed loss
[libx264 @ 0x563aeeda6980] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x563aeeda6980] profile High, level 4.2, 4:2:0, 8-bit
[libx264 @ 0x563aeeda6980] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=18 lookahead_threads=3 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/tmp/aimpro/1613/with_pip_part-2.MP4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1920x1080, q=2-31, 59.94 fps, 60k tbn (default)
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
  Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 229 kb/s (default)
    Metadata:
      handler_name    : Core Media Audio
      vendor_id       : [0][0][0][0]
frame=  419 fps= 49 q=-1.0 Lsize=    3630kB time=00:00:06.99 bitrate=4252.8kbits/s speed=0.812x
video:3422kB audio:196kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.343871%
[libx264 @ 0x563aeeda6980] frame I:2     Avg QP:23.77  size:124780
[libx264 @ 0x563aeeda6980] frame P:105   Avg QP:25.32  size: 19702
[libx264 @ 0x563aeeda6980] frame B:312   Avg QP:28.64  size:  3797
[libx264 @ 0x563aeeda6980] consecutive B-frames:  0.7%  0.0%  0.0% 99.3%
[libx264 @ 0x563aeeda6980] mb I  I16..4:  9.3% 66.8% 24.0%
[libx264 @ 0x563aeeda6980] mb P  I16..4:  0.6%  2.4%  0.5%  P16..4: 37.5%  6.1%  4.1%  0.0%  0.0%    skip:48.8%
[libx264 @ 0x563aeeda6980] mb B  I16..4:  0.0%  0.2%  0.0%  B16..8: 20.2%  1.4%  0.3%  direct: 0.4%  skip:77.4%  L0:31.4% L1:64.7% BI: 3.9%
[libx264 @ 0x563aeeda6980] 8x8 transform intra:69.0% inter:83.1%
[libx264 @ 0x563aeeda6980] coded y,uvDC,uvAC intra: 61.8% 71.2% 31.2% inter: 5.4% 9.3% 0.3%
[libx264 @ 0x563aeeda6980] i16 v,h,dc,p: 19% 32%  8% 41%
[libx264 @ 0x563aeeda6980] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 17% 27% 14%  4%  7%  7% 13%  5%  7%
[libx264 @ 0x563aeeda6980] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 22% 29% 11%  4%  7%  6% 11%  5%  5%
[libx264 @ 0x563aeeda6980] i8c dc,h,v,p: 46% 24% 22%  7%
[libx264 @ 0x563aeeda6980] Weighted P-Frames: Y:0.0% UV:0.0%
[libx264 @ 0x563aeeda6980] ref P L0: 61.6% 14.2% 17.9%  6.3%
[libx264 @ 0x563aeeda6980] ref B L0: 92.3%  5.8%  1.8%
[libx264 @ 0x563aeeda6980] ref B L1: 95.6%  4.4%
[libx264 @ 0x563aeeda6980] kb/s:4009.08
ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)

In [53]:
if not pip: 
    def gen_concat_command(extract_cmds, output_file_name_path): 
        list_file_name=os.path.join(workspace_dir, 'part-list.txt')
        with open(list_file_name, 'w') as h: 
            for i in range(len(extract_cmds)):
                p=os.path.join(workspace_dir,f"part-{i}.MP4")  
                h.write(f"file '{p}' \n")
        txt=  f"ffmpeg -f concat -safe 0 -i {list_file_name} -c copy {output_file_name_path}"
        pyperclip.copy(txt)
        return txt 

    output_path_file=os.path.join(raw_video_dir,f'pip-test-{quater}.MP4')
    concat_cmd= gen_concat_command(process_extract_cmds, output_path_file)
    ! {concat_cmd}
else: 
    def gen_concat_command(output_file_name_path): 
        part_list=list(fnmatch.filter(os.listdir(workspace_dir), "with_pip_part*.MP4"))
        part_list.sort(key=part_sort_key)
        part_list=[os.path.join(workspace_dir, p) for p in part_list]
        list_file_name=os.path.join(workspace_dir, 'part-list.txt')
        with open(list_file_name, 'w') as h: 
            for p  in part_list:
                h.write(f"file '{p}' \n")

        txt=  f"ffmpeg -f concat -safe 0 -i {list_file_name} -c copy {output_file_name_path}"
        pyperclip.copy(txt)
        return txt 

    output_path_file=os.path.join(raw_video_dir,f'war-vs-knox-{quater}.MP4')
    concat_cmd= gen_concat_command(output_path_file)
    ! {concat_cmd}

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x58f4948121c0] Auto-inserting h264_mp4toannexb bitstream filter
Input #0, concat, from '/tmp/aimpro/1613/part-list.txt':
  Duration: N/A, start: -0.044000, bitrate: 3660 kb/s
  Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080, 3455 kb/s, 59.94 fps, 59.94 tbr, 60k tbn, 119.88 tbc
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 205 kb/s
    Metadata:
      handler_name    : Core Media Audio
      vendor_id       : [0][0][0][0]
File '/mnt/c/data/temp/aimpro_raw_video/war-vs-knox-1.MP4' already exists. Overwrite? [y/N] ^C

In [ ]:
! rm -rf {workspace_dir}

In [104]:
#compress. 
#!ffmpeg -i {output_path_file} -c:v libx265 -crf 28 -preset slow -c:a aac -tag:v hvc1 -b:a 128k 265-{output_path_file}